/**
 * 初期種目。刻み・レップ範囲・休憩はここが初期値で、あとから種目ごとに直せる。
 *
 * レップ範囲は意図的に狭くしてある（複合種目で 2〜3、単関節で 3〜4）。
 * 範囲が広いと、上限を達成して負荷を上げた日にレップが大きく落ち、
 * その 1 日だけ総ボリュームが目に見えて減る。続けている実感を削るので狭く取る。
 *
 * guide は読み物で、利用者が書き換えるものではない（自分用のメモは tips 側）。
 * やり方は「思い出せる程度」に留める。ここで長文を読ませても、ジムでは読まない。
 */

import { exerciseId, type Exercise, type Guide } from './types.ts';

type Preset = Omit<Exercise, 'id' | 'archived' | 'tips' | 'updatedAt'> & {
  slug: string;
  guide: Guide;
};

const PRESETS: readonly Preset[] = [
  // ── 胸 ───────────────────────────────────────────
  {
    slug: 'bench-press',
    name: 'ベンチプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 6,
    repMax: 8,
    sets: 3,
    restSec: 180,
    guide: {
      howTo: 'ベンチに仰向けで、肩幅より広くバーを握る。みぞおちの上あたりへ下ろし、足で床を押しながら押し上げる。',
      primary: ['chest'],
      secondary: ['frontDelt', 'triceps'],
      cues: [
        '肩甲骨を寄せて下げ、胸を天井に向けたまま固定する',
        '肘を真横に開かず、脇を 45 度くらいに保つ',
        'バーを下ろす位置は鎖骨ではなくみぞおち寄り',
      ],
    },
  },
  {
    slug: 'incline-press',
    name: 'インクラインプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '30〜45 度に起こしたベンチで押す。角度が上がるほど胸の上部と肩に寄る。',
      primary: ['chest', 'frontDelt'],
      secondary: ['triceps'],
      cues: ['角度は 30 度前後から。45 度を超えると肩の種目に近づく', '鎖骨の少し下に向けて下ろす', '腰を反らせて逃げない'],
    },
  },
  {
    slug: 'smith-incline-bench-press',
    name: 'スミスマシン・インクラインベンチプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '軌道が固定されたスミスマシンでインクラインプレス。バランスを取らなくてよいぶん胸に集中できる。',
      primary: ['chest', 'frontDelt'],
      secondary: ['triceps'],
      cues: ['軌道に対してベンチの位置を先に合わせる（体の位置で軌道は変えられない）', '上げきる手前で止めて張りを保つ'],
    },
  },
  {
    slug: 'dumbbell-press',
    name: 'ダンベルプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: 'フラットベンチでダンベルを胸の横まで下ろし、弧を描いて押し上げる。バーより深く下ろせる。',
      primary: ['chest'],
      secondary: ['frontDelt', 'triceps'],
      cues: ['上で完全に閉じきらず、少し離して張りを残す', '手首を寝かせず、前腕を床と垂直に保つ'],
    },
  },
  {
    slug: 'incline-dumbbell-press',
    name: 'インクラインダンベルプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: '30 度前後のベンチでダンベルプレス。胸の上部を厚くしたいときの中心種目。',
      primary: ['chest', 'frontDelt'],
      secondary: ['triceps'],
      cues: ['肩がすくむ手前で止める', '肘を体の真横ではなくやや前に置く'],
    },
  },
  {
    slug: 'dumbbell-fly',
    name: 'ダンベルフライ',
    group: 'chest',
    loadMode: 'weight',
    increment: 2,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '肘を軽く曲げたまま腕を開き、胸のストレッチを感じてから閉じる。押す動きではなく閉じる動き。',
      primary: ['chest'],
      secondary: ['frontDelt'],
      cues: ['肘の角度を最初から最後まで変えない', '重量より可動域。開いたところで 1 秒止める'],
    },
  },
  {
    slug: 'pec-fly',
    name: 'ペックフライ',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: 'マシンで腕を閉じる。軌道が決まっているので、フライの中では一番胸だけに入れやすい。',
      primary: ['chest'],
      secondary: ['frontDelt'],
      cues: ['背中をパッドから離さない', '閉じきったところで止めて、戻すときはゆっくり'],
    },
  },
  {
    slug: 'cable-crossover',
    name: 'ケーブルクロスオーバー',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 75,
    guide: {
      howTo: '高い位置のケーブルを両手で持ち、体の前で斜め下に交差させる。最後まで負荷が抜けない。',
      primary: ['chest'],
      secondary: ['frontDelt'],
      cues: ['滑車の高さで効く場所が変わる（高い=下部、低い=上部）', '腕で引かず、脇を締める意識で'],
    },
  },
  {
    slug: 'chest-press',
    name: 'チェストプレス',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: 'マシンで座って押す。フォームの再現性が高いので、追い込む最後の種目に置きやすい。',
      primary: ['chest'],
      secondary: ['frontDelt', 'triceps'],
      cues: ['シート高はハンドルが胸の高さに来る位置', '肩を落として胸を張ってから押し始める'],
    },
  },
  {
    slug: 'dumbbell-pullover',
    name: 'ダンベルプルオーバー',
    group: 'chest',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: 'ベンチに仰向けで、ダンベル 1 つを両手で持ち、頭の後ろへ弧を描いて下ろして戻す。',
      primary: ['chest', 'lats'],
      secondary: ['triceps'],
      cues: ['肋骨を開くように大きく息を吸いながら下ろす', '肘を伸ばしきらず軽く曲げたまま'],
    },
  },

  // ── 背中 ─────────────────────────────────────────
  {
    slug: 'deadlift',
    name: 'デッドリフト',
    group: 'back',
    loadMode: 'weight',
    increment: 5,
    repMin: 4,
    repMax: 6,
    sets: 3,
    restSec: 240,
    guide: {
      howTo: 'バーをすねの近くに置き、股関節から曲げて握る。背中をまっすぐ保ったまま床を押して立ち上がる。',
      primary: ['lowerBack', 'glutes', 'hams'],
      secondary: ['lats', 'traps', 'quads'],
      cues: ['バーは常に体の近くを通す（すねを擦るくらい）', '腰から丸めず、胸を張って股関節から動かす', '引き上げるのではなく床を押す'],
    },
  },
  {
    slug: 'lat-pulldown',
    name: 'ラットプルダウン',
    group: 'back',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: '座ってバーを肩幅より広く握り、鎖骨に向けて引き下ろす。背中の幅を作る種目。',
      primary: ['lats'],
      secondary: ['midBack', 'biceps', 'rearDelt'],
      cues: ['腕で引く前に肩を下げる（肩甲骨を下制してから引く）', '胸を張って、少しだけ後傾する', '戻すときに肩がすくむのを許さない'],
    },
  },
  {
    slug: 'assist-chinning',
    name: 'アシストチンニング',
    group: 'back',
    loadMode: 'assist',
    increment: 2.5,
    repMin: 6,
    repMax: 9,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '補助のあるマシンで懸垂する。設定した補助重量ぶん体が軽くなるので、実際に引いているのは「体重 − 補助重量」。',
      primary: ['lats'],
      secondary: ['midBack', 'biceps', 'rearDelt'],
      cues: [
        '補助を下げるほど負荷が上がる。上限レップに届いたら補助を減らす',
        '肘を体の後ろへ引き、胸をバーに近づける',
        '下で完全に脱力せず、肩を入れたまま止める',
      ],
    },
  },
  {
    slug: 'barbell-row',
    name: 'ベントオーバーロー',
    group: 'back',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '股関節から前傾して上体を 45 度前後に保ち、バーをへそに向けて引く。背中の厚みを作る種目。',
      primary: ['midBack', 'lats'],
      secondary: ['biceps', 'lowerBack', 'rearDelt'],
      cues: ['引く動作で上体を起こさない（角度を固定する）', '肘を後ろに引き、肩甲骨を寄せる', '反動を使わず、下で止めてから引く'],
    },
  },
  {
    slug: 'seated-row',
    name: 'シーテッドロー',
    group: 'back',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '座って足を突っ張り、ハンドルを腹に向けて引く。上体の角度を固定できるので背中に入れやすい。',
      primary: ['midBack', 'lats'],
      secondary: ['biceps', 'rearDelt'],
      cues: ['上体を大きく倒して反動をつけない', '引ききったところで肩甲骨を寄せて 1 秒止める'],
    },
  },
  {
    slug: 'one-hand-row',
    name: 'ワンハンドローイング',
    group: 'back',
    loadMode: 'weight',
    increment: 2,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: 'ベンチに片手をついて上体を支え、反対の手でダンベルを腰に向けて引く。片側ずつ可動域を大きく取れる。',
      primary: ['lats', 'midBack'],
      secondary: ['biceps', 'rearDelt'],
      cues: ['体をひねって上げない。骨盤と肩を床と平行に保つ', '肘を体の後ろまで引き切る', '下ろすときに肩を落として広背筋を伸ばす'],
    },
  },
  {
    slug: 'dumbbell-row',
    name: 'ダンベルローイング',
    group: 'back',
    loadMode: 'weight',
    increment: 2,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '両手にダンベルを持ち、前傾を保ったまま両側同時に引く。',
      primary: ['midBack', 'lats'],
      secondary: ['biceps', 'rearDelt'],
      cues: ['上体の角度を最後まで変えない', '手のひらを向かい合わせにすると脇に入りやすい'],
    },
  },

  // ── 肩 ───────────────────────────────────────────
  {
    slug: 'shoulder-press',
    name: 'ショルダープレス',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '座位または立位で、肩の高さから真上へ押し上げる。肩の前と横を厚くする中心種目。',
      primary: ['frontDelt', 'sideDelt'],
      secondary: ['triceps', 'traps'],
      cues: ['腰を反らせて胸で押さない', '耳の横を通す軌道で真上に', '上げきる手前で止めて肩の張りを保つ'],
    },
  },
  {
    slug: 'dumbbell-shoulder-press',
    name: 'ダンベルショルダープレス',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: 'ダンベルで真上へ押す。軌道が自由なぶん可動域を取りやすい。',
      primary: ['frontDelt', 'sideDelt'],
      secondary: ['triceps'],
      cues: ['肘を真横に開きすぎない（やや前）', '下ろすのは耳の高さまでで十分'],
    },
  },
  {
    slug: 'smith-shoulder-press',
    name: 'スミスショルダープレス',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '軌道が固定されたスミスマシンで押す。バランスを取らずに肩へ集中できる。',
      primary: ['frontDelt', 'sideDelt'],
      secondary: ['triceps'],
      cues: ['軌道に対してベンチを前後させて位置を合わせる', '首をすくめず、肩を下げたまま押す'],
    },
  },
  {
    slug: 'arnold-press',
    name: 'アーノルドプレス',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: '手のひらを自分に向けた位置から、回しながら押し上げる。前部から中部まで通して使う。',
      primary: ['frontDelt', 'sideDelt'],
      secondary: ['triceps'],
      cues: ['回す動作を押し上げと同時に行う', '重量は普通のプレスより落とす'],
    },
  },
  {
    slug: 'side-raise',
    name: 'サイドレイズ',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 1,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'ダンベルを体の横から肩の高さまで上げる。肩幅の見え方を作る種目。',
      primary: ['sideDelt'],
      secondary: ['traps'],
      cues: ['小指側から上げる意識で、親指を少し下げる', '肩の高さより上げない（そこから先は僧帽筋）', '反動が出るなら重量を落とす。ここは軽さで効かせる'],
    },
  },
  {
    slug: 'front-raise',
    name: 'フロントレイズ',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 1,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'ダンベルを体の前から肩の高さまで上げる。',
      primary: ['frontDelt'],
      secondary: ['chest'],
      cues: ['腰を反らせて振り上げない', '肘を軽く曲げたまま固定する'],
    },
  },
  {
    slug: 'rear-raise',
    name: 'リアレイズ',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 1,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: '前傾して腕を後ろ斜め上へ開く。姿勢と後ろ姿に効く、見落とされやすい部位。',
      primary: ['rearDelt'],
      secondary: ['midBack', 'traps'],
      cues: ['肩甲骨を寄せる動きではなく、腕を開く動きにする', '首をすくめない', '軽い重量で 15 回できる範囲から'],
    },
  },
  {
    slug: 'rear-deltoid',
    name: 'リアデルトイド',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'マシンで腕を後ろへ開く（ペックフライの逆向き）。軌道が決まるのでリアレイズより狙いやすい。',
      primary: ['rearDelt'],
      secondary: ['midBack'],
      cues: ['胸をパッドにつけたまま動かす', '腕を伸ばしきらず、肘は軽く曲げる'],
    },
  },
  {
    slug: 'cable-face-pull',
    name: 'ケーブルフェイスプル',
    group: 'shoulders',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: '顔の高さのロープを、両手を開きながら顔の横へ引く。肩の後ろと姿勢に効く。',
      primary: ['rearDelt'],
      secondary: ['traps', 'midBack'],
      cues: ['肘を高く保ち、手を耳の横まで', '引ききったところで外旋（手を後ろへ回す）を足す'],
    },
  },

  // ── 腕 ───────────────────────────────────────────
  {
    slug: 'barbell-curl',
    name: 'バーベルカール',
    group: 'arms',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '肩幅でバーを持ち、肘を体の横に固定したまま曲げる。',
      primary: ['biceps'],
      secondary: ['forearm'],
      cues: ['肘を前に出さない（出すと負荷が抜ける）', '体を反らせて振り上げない', '下ろすときを 2 秒かけて効かせる'],
    },
  },
  {
    slug: 'arm-curl',
    name: 'アームカール',
    group: 'arms',
    loadMode: 'weight',
    increment: 2,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'ダンベルで片手ずつ、または交互に曲げる。手のひらを返しながら上げると二頭に入りやすい。',
      primary: ['biceps'],
      secondary: ['forearm'],
      cues: ['上げきったところで手首を少し外に返す', '肩を前に出して補助しない'],
    },
  },
  {
    slug: 'lying-extension',
    name: 'ライイングエクステンション',
    group: 'arms',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 75,
    guide: {
      howTo: '仰向けで肘を天井に向けて固定し、額の後ろへ下ろして伸ばす。三頭の長頭に入る。',
      primary: ['triceps'],
      secondary: [],
      cues: ['肘の位置を動かさない', '肘を伸ばしきる手前で止めず、最後まで伸ばす', '肘に痛みが出るなら角度を変える'],
    },
  },
  {
    slug: 'cable-pushdown',
    name: 'ケーブルプレスダウン',
    group: 'arms',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: '高い位置のケーブルを、肘を体の横に固定したまま押し下げる。',
      primary: ['triceps'],
      secondary: [],
      cues: ['肘を脇に固定して動かさない', '上体を前に倒して体重で押さない', '下で 1 秒止めて絞る'],
    },
  },

  // ── 脚 ───────────────────────────────────────────
  {
    slug: 'squat',
    name: 'スクワット',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 6,
    repMax: 8,
    sets: 3,
    restSec: 240,
    guide: {
      howTo: 'バーを肩に乗せ、股関節と膝を同時に曲げて座り、立ち上がる。',
      primary: ['quads', 'glutes'],
      secondary: ['hams', 'lowerBack', 'abs'],
      cues: ['膝を前に出すのと股関節を引くのを同時に始める', '足裏全体で床を押す（かかと寄りに感じる程度）', '深さは腰が丸まらない範囲まで'],
    },
  },
  {
    slug: 'hack-squat',
    name: 'ハックスクワット',
    group: 'legs',
    loadMode: 'weight',
    increment: 5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 180,
    guide: {
      howTo: '斜めの軌道のマシンで、背中を支えたままスクワットする。バランスを取らずに脚を追い込める。',
      primary: ['quads'],
      secondary: ['glutes', 'hams'],
      cues: ['足の位置が高いと尻・低いと前もも寄り', '腰をパッドから離さない', '膝を伸ばしきってロックしない'],
    },
  },
  {
    slug: 'smith-squat',
    name: 'スミスマシン・バーベルスクワット',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 180,
    guide: {
      howTo: '軌道が固定されたスミスマシンでスクワット。足を少し前に置くと安定する。',
      primary: ['quads', 'glutes'],
      secondary: ['hams'],
      cues: ['足の前後位置で効く場所が変わる。まず位置を決めてから重量を上げる', '軌道に逆らわず、まっすぐ上下する'],
    },
  },
  {
    slug: 'leg-press',
    name: 'レッグプレス',
    group: 'legs',
    loadMode: 'weight',
    increment: 5,
    repMin: 10,
    repMax: 12,
    sets: 3,
    restSec: 120,
    guide: {
      howTo: 'シートに座り、プレートを脚で押す。腰の負担が少なく高重量を扱える。',
      primary: ['quads', 'glutes'],
      secondary: ['hams'],
      cues: ['腰が浮くところまで深く下ろさない', '膝を伸ばしきってロックしない', '足幅が広いと内側と尻、狭いと前もも'],
    },
  },
  {
    slug: 'leg-extension',
    name: 'レッグエクステンション',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '座って膝を伸ばす。前ももの形を作る単関節種目。',
      primary: ['quads'],
      secondary: [],
      cues: ['伸ばしきったところで 1 秒止める', '反動で振り上げない。重量より止める時間'],
    },
  },
  {
    slug: 'leg-curl',
    name: 'レッグカール',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 15,
    sets: 3,
    restSec: 90,
    guide: {
      howTo: '膝を曲げて裏ももを縮める。前ももだけ鍛えると崩れるバランスを埋める。',
      primary: ['hams'],
      secondary: ['calves'],
      cues: ['尻を浮かせて反動をつけない', '戻すときをゆっくり。伸ばされる側で効く'],
    },
  },
  {
    slug: 'romanian-deadlift',
    name: 'ルーマニアンデッドリフト',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 8,
    repMax: 10,
    sets: 3,
    restSec: 150,
    guide: {
      howTo: '膝を軽く曲げたまま、股関節から上体を倒してバーを下ろす。裏ももと尻のストレッチで効かせる。',
      primary: ['hams', 'glutes'],
      secondary: ['lowerBack'],
      cues: ['膝の角度を変えない（スクワットにしない）', '裏ももが伸びきる手前で止めて戻す', '背中は最後までまっすぐ'],
    },
  },
  {
    slug: 'calf-raise',
    name: 'カーフレイズ',
    group: 'legs',
    loadMode: 'weight',
    increment: 2.5,
    repMin: 12,
    repMax: 16,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'つま先立ちでかかとを上げ下げする。脚のシルエットを締める部位。',
      primary: ['calves'],
      secondary: [],
      cues: ['一番下まで下ろしてから上げる（可動域が短いので削らない）', '上で 1 秒止める'],
    },
  },

  // ── 体幹 ─────────────────────────────────────────
  {
    slug: 'ab-roller',
    name: 'アブローラー',
    group: 'core',
    loadMode: 'bodyweight',
    increment: 2.5,
    repMin: 8,
    repMax: 12,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: '膝または立位からローラーを前に転がし、腰を反らせずに戻る。',
      primary: ['abs'],
      secondary: ['obliques', 'lats', 'frontDelt'],
      cues: ['腰を反らせない。反るなら転がす距離を短くする', '骨盤を後傾させ、みぞおちを丸めたまま'],
    },
  },
  {
    slug: 'hanging-leg-raise',
    name: 'ハンギングレッグレイズ',
    group: 'core',
    loadMode: 'bodyweight',
    increment: 2.5,
    repMin: 8,
    repMax: 12,
    sets: 3,
    restSec: 60,
    guide: {
      howTo: 'バーにぶら下がり、脚を持ち上げる。下腹部に入れやすい。',
      primary: ['abs'],
      secondary: ['obliques', 'forearm'],
      cues: ['脚の高さより骨盤を丸めることを優先する', '振り子にならないよう、下で止めてから上げる'],
    },
  },
];

const GUIDES = new Map<string, Guide>(PRESETS.map((p) => [p.slug, p.guide]));

/** 種目の説明。プリセットに無い（自分で足した）種目には無い。 */
export function guideFor(id: string): Guide | undefined {
  return GUIDES.get(id);
}

export function presetExercises(): Exercise[] {
  // tips は空で始める。埋めるのは実際にやってみて分かったことなので、こちらでは書かない
  return PRESETS.map(({ slug, guide: _guide, ...rest }) => ({
    ...rest,
    id: exerciseId(slug),
    tips: '',
    archived: false,
    updatedAt: 0,
  }));
}

/**
 * 上の並び順。IndexedDB から読むと id 順になって意図した並びが失われるので、
 * まだ一度もやっていない種目の並べ替えにこれを使う。
 */
export const PRESET_ORDER: readonly string[] = PRESETS.map((p) => p.slug);
